- name: Install and Run Nginx
  hosts: web
  become: true
  tasks:
  - name: Install Nginx
    package:
      name: nginx
      state: present

  - name: Start nginx
    service:
      name: nginx
      state: started
      enabled: yes
