- name: Install and start nginx
  hosts: local
  connection: local
  become: true
  tasks:
  - name: Install nginx in debian os
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"

  - name: install nginx in redhat os
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: Start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
