- name: Loops in ansible
  hosts: local
  connection: local
  vars:
    NAMES:
    - mahi
    - bob
    - alice
    - ram
    - veer
  tasks:
  - name: print info using loops
    ansible.builtin.debug:
      msg: "Hello {{items}}"
    loop: NAMES
