- name: Install multiple packages using loops
  hosts: local
  connection: local
  become: true
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - nginx
    - mysql
    - tree
    - htop
