- name: Install and Run nginx
  hosts: all
  become: yes
  serial: 5
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: Running nginx
    ansible.builtin.service:
      name: nginx
      state: started
